#######################################
# Annotations - example configuration #
#######################################

Annotations:
    # You can overwrite the default driver by providing your own.
    # How to create a new driver, read in the Readme.md file.
    # If you don't wish to change the default driver,
    # just ommit this definition in your config file.
    Bridge: \Webiny\Component\Annotations\Bridge\Minime\Annotations
    # Entries under ClassLoader are automatically registered
    # with ClassLoader. You don't need this part if you are using Composer autoload.
    ClassLoader:
        Minime\Annotations: /var/www/Vendors/Minime/Annotations/src